# Generated by Django 4.1.6 on 2023-02-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbti',
            field=models.CharField(default='ISFP', max_length=100),
            preserve_default=False,
        ),
    ]
